name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a specific Python version, e.g., '3.9'

      - name: Install MkDocs and dependencies
        run: pip install mkdocs mkdocs-material # Add any other plugins/themes here

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # Deploy only from the main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # The directory where MkDocs builds the site